# Generated by Django 4.2.11 on 2024-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('genre', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('bookshelves', models.CharField(max_length=50)),
                ('subjects', models.TextField()),
                ('mime_type', models.CharField(max_length=32)),
                ('download_links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('birth_year', models.SmallIntegerField(null=True)),
                ('death_year', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('download_count', models.IntegerField()),
                ('gutenberg_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=16)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='book_authors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book_bookshelves',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('bookshelf_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book_languages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book_subjects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bookshelf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='format',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mime_type', models.CharField(max_length=32)),
                ('url', models.TextField()),
                ('book_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
