# Generated by Django 4.2.11 on 2024-03-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_book',
            name='genre',
            field=models.CharField(max_length=255),
        ),
    ]
