# Generated by Django 4.2.11 on 2024-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_all_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_book',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
